package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/iron-io/functions_go/client/apps"
	"github.com/iron-io/functions_go/client/routes"
	"github.com/iron-io/functions_go/client/tasks"
	"github.com/iron-io/functions_go/client/version"
)

// Default functions HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new functions HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Functions {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("127.0.0.1:8080", "/v1", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new functions client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Functions {
	cli := new(Functions)
	cli.Transport = transport

	cli.Apps = apps.New(transport, formats)

	cli.Routes = routes.New(transport, formats)

	cli.Tasks = tasks.New(transport, formats)

	cli.Version = version.New(transport, formats)

	return cli
}

// Functions is a client for functions
type Functions struct {
	Apps *apps.Client

	Routes *routes.Client

	Tasks *tasks.Client

	Version *version.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Functions) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Apps.SetTransport(transport)

	c.Routes.SetTransport(transport)

	c.Tasks.SetTransport(transport)

	c.Version.SetTransport(transport)

}
