/* 
 * IronFunctions
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.1.28
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package functions

type Route struct {

	// URL path that will be matched to this route
	Path string `json:"path,omitempty"`

	// Name of Docker image to use in this route. You should include the image tag, which should be a version number, to be more accurate. Can be overridden on a per route basis with route.image.
	Image string `json:"image,omitempty"`

	// Map of http headers that will be sent with the response
	Headers map[string][]string `json:"headers,omitempty"`

	// Max usable memory for this route (MiB).
	Memory int64 `json:"memory,omitempty"`

	// Route type
	Type_ string `json:"type,omitempty"`

	// Payload format sent into function.
	Format string `json:"format,omitempty"`

	// Maximum number of hot containers concurrency
	MaxConcurrency int32 `json:"max_concurrency,omitempty"`

	// Route configuration - overrides application configuration
	Config map[string]string `json:"config,omitempty"`

	// Timeout for executions of this route. Value in Seconds
	Timeout int32 `json:"timeout,omitempty"`
}
