package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/iron-io/functions_go/models"
)

// PostAppsAppRoutesReader is a Reader for the PostAppsAppRoutes structure.
type PostAppsAppRoutesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAppsAppRoutesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAppsAppRoutesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostAppsAppRoutesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostAppsAppRoutesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostAppsAppRoutesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostAppsAppRoutesCreated creates a PostAppsAppRoutesCreated with default headers values
func NewPostAppsAppRoutesCreated() *PostAppsAppRoutesCreated {
	return &PostAppsAppRoutesCreated{}
}

/*PostAppsAppRoutesCreated handles this case with default header values.

Route created
*/
type PostAppsAppRoutesCreated struct {
	Payload *models.RouteWrapper
}

func (o *PostAppsAppRoutesCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/routes][%d] postAppsAppRoutesCreated  %+v", 201, o.Payload)
}

func (o *PostAppsAppRoutesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAppsAppRoutesBadRequest creates a PostAppsAppRoutesBadRequest with default headers values
func NewPostAppsAppRoutesBadRequest() *PostAppsAppRoutesBadRequest {
	return &PostAppsAppRoutesBadRequest{}
}

/*PostAppsAppRoutesBadRequest handles this case with default header values.

One or more of the routes were invalid due to parameters being missing or invalid.
*/
type PostAppsAppRoutesBadRequest struct {
	Payload *models.Error
}

func (o *PostAppsAppRoutesBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/routes][%d] postAppsAppRoutesBadRequest  %+v", 400, o.Payload)
}

func (o *PostAppsAppRoutesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAppsAppRoutesInternalServerError creates a PostAppsAppRoutesInternalServerError with default headers values
func NewPostAppsAppRoutesInternalServerError() *PostAppsAppRoutesInternalServerError {
	return &PostAppsAppRoutesInternalServerError{}
}

/*PostAppsAppRoutesInternalServerError handles this case with default header values.

Could not accept routes due to internal error.
*/
type PostAppsAppRoutesInternalServerError struct {
	Payload *models.Error
}

func (o *PostAppsAppRoutesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/routes][%d] postAppsAppRoutesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAppsAppRoutesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAppsAppRoutesDefault creates a PostAppsAppRoutesDefault with default headers values
func NewPostAppsAppRoutesDefault(code int) *PostAppsAppRoutesDefault {
	return &PostAppsAppRoutesDefault{
		_statusCode: code,
	}
}

/*PostAppsAppRoutesDefault handles this case with default header values.

Unexpected error
*/
type PostAppsAppRoutesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post apps app routes default response
func (o *PostAppsAppRoutesDefault) Code() int {
	return o._statusCode
}

func (o *PostAppsAppRoutesDefault) Error() string {
	return fmt.Sprintf("[POST /apps/{app}/routes][%d] PostAppsAppRoutes default  %+v", o._statusCode, o.Payload)
}

func (o *PostAppsAppRoutesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
