package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// AppWrapper app wrapper
// swagger:model AppWrapper
type AppWrapper struct {

	// app
	// Required: true
	App *App `json:"app"`
}

// Validate validates this app wrapper
func (m *AppWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApp(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppWrapper) validateApp(formats strfmt.Registry) error {

	if err := validate.Required("app", "body", m.App); err != nil {
		return err
	}

	if m.App != nil {

		if err := m.App.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
