package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ErrorBody error body
// swagger:model ErrorBody
type ErrorBody struct {

	// fields
	// Read Only: true
	Fields string `json:"fields,omitempty"`

	// message
	// Read Only: true
	Message string `json:"message,omitempty"`
}

// Validate validates this error body
func (m *ErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
