// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TaskAllOf1 task all of1
// swagger:model taskAllOf1

type TaskAllOf1 struct {

	// Time when task completed, whether it was successul or failed. Always in UTC.
	CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

	// Time when task was submitted. Always in UTC.
	// Read Only: true
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Env vars for the task. Comes from the ones set on the Group.
	EnvVars map[string]string `json:"env_vars,omitempty"`

	// The error message, if status is 'error'. This is errors due to things outside the task itself. Errors from user code will be found in the log.
	Error string `json:"error,omitempty"`

	// Group this task belongs to.
	// Read Only: true
	GroupName string `json:"group_name,omitempty"`

	// Machine usable reason for task being in this state.
	// Valid values for error status are `timeout | killed | bad_exit`.
	// Valid values for cancelled status are `client_request`.
	// For everything else, this is undefined.
	//
	Reason string `json:"reason,omitempty"`

	// If this field is set, then this task was retried by the task referenced in this field.
	// Read Only: true
	RetryAt string `json:"retry_at,omitempty"`

	// If this field is set, then this task is a retry of the ID in this field.
	// Read Only: true
	RetryOf string `json:"retry_of,omitempty"`

	// Time when task started execution. Always in UTC.
	StartedAt strfmt.DateTime `json:"started_at,omitempty"`
}

/* polymorph taskAllOf1 completed_at false */

/* polymorph taskAllOf1 created_at false */

/* polymorph taskAllOf1 env_vars false */

/* polymorph taskAllOf1 error false */

/* polymorph taskAllOf1 group_name false */

/* polymorph taskAllOf1 reason false */

/* polymorph taskAllOf1 retry_at false */

/* polymorph taskAllOf1 retry_of false */

/* polymorph taskAllOf1 started_at false */

// Validate validates this task all of1
func (m *TaskAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var taskAllOf1TypeReasonPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["timeout","killed","bad_exit","client_request"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		taskAllOf1TypeReasonPropEnum = append(taskAllOf1TypeReasonPropEnum, v)
	}
}

const (
	// TaskAllOf1ReasonTimeout captures enum value "timeout"
	TaskAllOf1ReasonTimeout string = "timeout"
	// TaskAllOf1ReasonKilled captures enum value "killed"
	TaskAllOf1ReasonKilled string = "killed"
	// TaskAllOf1ReasonBadExit captures enum value "bad_exit"
	TaskAllOf1ReasonBadExit string = "bad_exit"
	// TaskAllOf1ReasonClientRequest captures enum value "client_request"
	TaskAllOf1ReasonClientRequest string = "client_request"
)

// prop value enum
func (m *TaskAllOf1) validateReasonEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, taskAllOf1TypeReasonPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TaskAllOf1) validateReason(formats strfmt.Registry) error {

	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	// value enum
	if err := m.validateReasonEnum("reason", "body", m.Reason); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskAllOf1) UnmarshalBinary(b []byte) error {
	var res TaskAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
